[package]
name = "cuda-imgproc"
version = "0.1.0"
edition = "2021"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"

[dependencies]
image = "0.25.2"
libloading = "0.8"
anyhow = "1.0.44"
env_logger = "0.11.5"
log = "0.4.22"
